name: todo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.3
  intl: ^0.20.2
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  build_runner: ^2.4.15
  freezed: ^3.0.4
  freezed_annotation: ^3.0.0
  go_router: ^14.8.1
  flutter_svg: ^2.0.17
  firebase_core: ^3.12.1
  firebase_auth: 5.5.1
  cloud_firestore: ^5.6.5
  firebase_messaging: ^15.2.4
  firebase_analytics: ^11.4.4
  android_alarm_manager_plus: ^4.0.7
  flutter_secure_storage: ^9.2.4
  flutter_local_notifications: ^19.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

dependency_overrides:
  intl: ^0.20.1

flutter:

  uses-material-design: true


  assets:
    - assets/icons/

flutter_intl:
  enabled: true